# Generated by Django 3.2.1 on 2021-05-11 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='static/assets/img/user_default.png', upload_to='static/assets/img')),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('address', models.TextField(max_length=300)),
                ('address2', models.TextField(max_length=255)),
                ('city', models.TextField(max_length=255)),
                ('pincode', models.IntegerField()),
                ('prop_type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('area', models.CharField(default=0, max_length=255)),
                ('bed', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('published', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sliderimg', models.ImageField(default='F:/COLLEGE/Degree/Projects/Python/realestate/static/img/placeholder.png', upload_to='static/assets/img')),
                ('image', models.ImageField(default='F:/COLLEGE/Degree/Projects/Python/realestate/static/img/placeholder.png', upload_to='static/assets/img')),
                ('floorplan', models.ImageField(default='F:/COLLEGE/Degree/Projects/Python/realestate/static/img/placeholder.png', upload_to='static/assets/img/floorplan')),
                ('agent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='estate.agents')),
            ],
        ),
    ]
