# Generated by Django 3.2.1 on 2021-05-11 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_alter_agents_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='created',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='email',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='published',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='agents',
            name='surname',
        ),
    ]
