# Generated by Django 3.2.1 on 2021-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_auto_20210511_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='floorplan',
            field=models.ImageField(default='about-1.jpg', upload_to='floorplan/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='property-5.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sliderimg',
            field=models.ImageField(default='slide-3.jpg', upload_to=''),
        ),
    ]
