# Generated by Django 3.2.1 on 2021-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_auto_20210512_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='image',
            field=models.ImageField(default='user_default.png', upload_to=''),
        ),
    ]
