# Generated by Django 3.2.1 on 2021-05-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_alter_agents_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='image',
            field=models.ImageField(default='user_default.png', upload_to='static/assets/img/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='floorplan',
            field=models.ImageField(default='about-1.jpg', upload_to='static/assets/img/floorplan/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='property-5.jpg', upload_to='static/assets/img/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sliderimg',
            field=models.ImageField(default='slide-3.jpg', upload_to='static/assets/img/'),
        ),
    ]
