# Generated by Django 3.2.1 on 2021-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0007_auto_20210512_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='image',
            field=models.ImageField(default='user_default.png', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='floorplan',
            field=models.ImageField(default='about-1.jpg', upload_to='img/floorplan/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='image',
            field=models.ImageField(default='property-5.jpg', upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='sliderimg',
            field=models.ImageField(default='slide-3.jpg', upload_to='img/'),
        ),
    ]
