# Generated by Django 3.2.1 on 2021-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0016_alter_message_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('comment', models.TextField(max_length=300)),
            ],
        ),
    ]
