# Generated by Django 3.2.1 on 2021-05-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0017_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='address2',
            field=models.TextField(max_length=350),
        ),
        migrations.AlterField(
            model_name='properties',
            name='content',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='properties',
            name='title',
            field=models.CharField(max_length=350),
        ),
    ]
